version: '3'
services:
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A celeryworker worker -l INFO --hostname=Tùng001@%h --concurrency=10 -Q render_content
    volumes:
      - .:/app
    networks:
      - app_network

  voicevox_engine:
    container_name: voicevox_engine
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    restart: always
    ports:
      - "127.0.0.1:50021:50021"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - app_network
