services:
  daphne:
    container_name: daphne
    restart: always
    env_file: .env
    build:
      context: .
    volumes:
      - .:/app
      - /mnt/raid0:/mnt/raid0
    depends_on:
      - redis2
    networks:
      - web_network
      - db_network
  nginx:
    container_name: newspro
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085" # Mapping port 5085 on host to port 80 in the container
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
      - db_network
    depends_on:
      - daphne

  redis2:
    container_name: redis2
    restart: always
    image: "redis:latest"
    ports:
      - "6530:6379"
    command: redis-server --appendonly yes
    networks:
      - web_network
      - db_network
  celery:
    container_name: celery_worker_tung
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    command: celery -A core worker -l INFO --hostname=worker1@%h --concurrency=5
    networks:
      - web_network
      - db_network

  flower:
    container_name: flower
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: celery -A core flower
    networks:
      - web_network
      - db_network

volumes:
  media_volume:
    driver: local

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
