services:
  celery_render:
    container_name: celery_render
    restart: always
    build:
      context: .
    command: python start_celery_content.py
    volumes:
      - .:/app
    network_mode: "host"
  voicevox_render:
    container_name: voicevox_render
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    restart: always
    ports:
      - "50025:50025"  # Thêm ports mapping
    volumes:
      - .:/app