services:
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A celeryworker worker -l INFO --hostname=worker@%h --concurrency=1 -Q render_video_reupload,render_video_content 
    volumes:
      - .:/app
    environment:  # Thêm phần này
      - DD_USE_TZ=false  # Thiết lập biến môi trường

  voicevox:
    container_name: voicevox
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "127.0.0.1:50021:50021"
    restart: always 
    volumes:
      - .:/app
      
  # voicevox_engine:
  #   container_name: voicevox_engine
  #   image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
  #   restart: always
  #   ports:
  #     - "127.0.0.1:50021:50021"
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [ gpu ]