version: '3'
services:
  redis_task:
    container_name: redis_task
    restart: always
    image: "redis:latest"
    ports:
      - "6530:6379"
    networks:
      - app_network

  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A celeryworker worker -l INFO --hostname=Tùng001@%h --concurrency=10 -Q render_content
    volumes:
      - .:/app
    depends_on:
      - redis_task
    environment:
      - CELERY_BROKER_URL=redis://redis_task:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_task:6379/0
    networks:
      - app_network

  voicevox_engine:
    container_name: voicevox_engine
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    restart: always
    ports:
      - "127.0.0.1:50021:50021"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
