version: '3.8'
services:
  video_screen:
    build:
      context: .
    container_name: video_screen
    volumes:
      - .:/app
    command: sh /app/download.sh
    healthcheck:
      test: ["CMD", "test", "-f", "/app/video_screen/ready.txt"]
      interval: 1m30s
      timeout: 20s
      retries: 5

  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A celeryworker worker -l INFO --hostname=worker222@%h --concurrency=4 -Q render_video_reupload,render_video_content  
    volumes:
      - .:/app
    

  voicevox:
    container_name: voicevox
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "127.0.0.1:50021:50021"
    restart: always 
    volumes:
      - .:/app