services:
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A celeryworker worker -l INFO --hostname=worker@%h --concurrency=1 -Q render_video_reupload,render_video_content 
    volumes:
      - .:/app
    environment:  # Thêm phần này
      - TZ=Asia/Ho_Chi_Minh  # Thiết lập múi giờ cho container

  voicevox:
    container_name: voicevox
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "127.0.0.1:50021:50021"
    restart: always 
    volumes:
      - .:/app
