services:
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A celeryworker worker -l INFO --hostname=Tùng001@%h --concurrency=3
    volumes:
      - .:/app

  voicevox:
    container_name: voicevox
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "127.0.0.1:50021:50021"
    restart: always 
    volumes:
      - .:/app
      
    