services:
  daphne_huan:
    container_name: daphne_huan
    restart: always
    env_file: .env
    build:
      context: .
    volumes:
      - .:/app
      - /mnt/raid0:/mnt/raid0
    depends_on:
      - redis
    networks:
      - web_network
      - db_network
  nginx:
    container_name: web_huan
    restart: always
    image: "nginx:latest"
    ports:
      - "8000:8000" # Mapping port 5085 on host to port 80 in the container
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
      - db_network
    depends_on:
      - daphne_huan

  redis:
    container_name: redis
    restart: always
    image: "redis:latest"
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    networks:
      - web_network
      - db_network
  flower_huan:
    container_name: flower_huan
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "7777:7777"
    command: celery -A core flower --port=7777
    networks:
      - web_network
      - db_network
volumes:
  media_volume:
    driver: local

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
