version: '3.8'
services:
  nginx:
    container_name: newspro
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  redis2:
    container_name: redis2
    restart: always
    image: "redis:latest"
    ports:
      - "6530:6379"
    command: redis-server --appendonly yes

  celery:
    container_name: celery_worker_tung
    build: .
    restart: always
    volumes:
      - ./media:/media
      - ./video_screen:/video_screen
      - .music_background:/music_background
    command: celery -A core worker -l INFO --hostname=worker1@%h --concurrency=2
    depends_on:
      - redis2

  daphne:
    container_name: daphne
    restart: always
    env_file: .env
    build: .
    volumes:
      - ./media:/media
    depends_on:
      - redis2

  voicevox_engine:
    container_name: voicevox_engine
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    ports:
      - '50021:50021'
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  flower:
    container_name: flower
    build: .
    restart: always
    ports:
      - "5555:5555"
    command: celery -A core flower
  # celery_beat:
  #   container_name: celery_beat
  #   build:
  #     context: .
  #   volumes:
  #     - .:/app
  #   command: celery -A core beat -l info
  #   networks:
  #     - db_network
  #     - web_network
  #   depends_on:
  #     - redis2

volumes:
  media_volume:
    driver: local
