version: '3.8'
services:
  daphne:
    container_name: daphne
    restart: always
    env_file: .env
    build:
      context: .
    volumes:
      - .:/app
    expose:
      - 5504
    networks:
      - web_network
      - db_network
  nginx:
    container_name: newspro
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - daphne
      - flower
    networks:
      - web_network
      - db_network

  redis2:
    container_name: redis2
    restart: always
    image: "redis:latest"
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    networks:
      - web_network
      - db_network

  celery:
    container_name: celery
    build:
      context: .
    volumes:
      - .:/app
    command: celery -A core.celery worker -l INFO --hostname=worker1@%h --concurrency=3
    networks:
      - web_network
      - db_network

  voicevox_engine:
    container_name: voicevox_engine
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    restart: always
    ports:
      - '50021:50021'
    networks:
      - web_network
      - db_network
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  flower:
    container_name: flower
    build:
      context: .
    ports:
      - "5555:5555"
    command: celery -A core.celery flower
    networks:
      - web_network
      - db_network

volumes:
  media_volume:
    driver: local

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
