version: '3.8'
services:
  nginx:
    container_name: nginx_tung
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./media:/media
      - ./static:/static
  redis2:
    container_name: redis2
    image: "redis:latest"
    command: redis-server --appendonly yes

  celery:
    container_name: celery_worker_tung
    build: .
    command: celery -A core worker -l INFO --hostname=worker1@%h

  daphne:
    container_name: daphne
    restart: always
    env_file: .env
    build: .
    volumes:
      - ./media:/media

  # voicevox_engine:
  #   container_name: voicevox_engine
  #   image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
  #   ports:
  #     - '50021:50021'
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [ gpu ]
  #   networks:
  #     - db_network
  #     - web_network

  flower:
    container_name: flower
    build: .
    expose:
      - "5555"
    ports:
      - "5555:5555"
    command: celery -A core flower
volumes:
  media_volume:
    driver: local
