services:
  celery_render:
    container_name: celery_render
    restart: always
    build:
      context: .
    command: python Start_celery_app.py
    volumes:
      - .:/app
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Sử dụng tất cả GPU có sẵn, hoặc có thể chỉ định số lượng cụ thể như 1,2,...
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Hoặc chỉ định GPU cụ thể như "0" hoặc "0,1"
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video  # Bao gồm khả năng mã hóa video
    
  voicevox_render:
    container_name: voicevox_render
    image: voicevox/voicevox_engine:nvidia-latest  # Đã cập nhật với tên đúng của image GPU
    ports:
      - "127.0.0.1:50021:50021"
    restart: always
    volumes:
      - .:/app
    runtime: nvidia  # Sử dụng GPU qua NVIDIA runtime
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Sử dụng tất cả GPU (có thể thay đổi để chỉ dùng 1 GPU, ví dụ: "0" cho GPU đầu tiên)
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Các khả năng GPU mà Docker cần sử dụng

