services:
  daphne_huan:
    container_name: daphne_huan
    restart: always
    env_file: .env
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - redis_huan
    networks:
      - web_network
      - db_network
    expose:
      - 5504
  nginx_huan:
    container_name: nginx_huan
    restart: always
    image: "nginx:latest"
    ports:
      - "8000:8000" # Mapping port 5085 on host to port 80 in the container
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
      - db_network
  redis_huan:
    container_name: redis_huan
    restart: always
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - web_network
      - db_network
  celery_huan:
    container_name: celery_worker_tung_huan
    build:
      context: .
    volumes:
      - .:/app
    command: celery -A core worker -l INFO --hostname=worker1@%h --concurrency=10
    networks:
      - web_network
      - db_network
  # voicevox_engine:
  #   container_name: voicevox_engine
  #   image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
  #   restart: always
  #   ports:
  #     - '50021:50021'
  #   networks:
  #     - web_network
  #     - db_network
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [ gpu ]

  flower_huan:
    container_name: flower_huan
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "6666:6666"
    command: celery -A core flower
    networks:
      - web_network
      - db_network

volumes:
  media_volume:
    driver: local

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
